In [10]:
import pandas as pd
import numpy as np
import psycopg2
import sqlalchemy as db
from sqlalchemy import create_engine
import yaml

In [11]:
with open('C:\\Users\\dylan\\OneDrive\\Documentos\\mensajeria\\config.yml', 'r') as f:
    config = yaml.safe_load(f)
    config_co = config['mensajeria']
    config_etl = config['ETL_PRO']

# Construct the database URL
url_co = (f"{config_co['drivername']}://{config_co['user']}:{config_co['password']}@{config_co['host']}:"
          f"{config_co['port']}/{config_co['dbname']}")
url_etl = (f"{config_etl['drivername']}://{config_etl['user']}:{config_etl['password']}@{config_etl['host']}:"
           f"{config_etl['port']}/{config_etl['dbname']}")
# Create the SQLAlchemy Engine
mensajeria = create_engine(url_co)
etl_conn = create_engine(url_etl)

In [12]:
dim_persona = pd.read_sql_table('clientes_datosmensajero', mensajeria)
dim_persona.head(10)

   datos_id
0         1
1         2
2         3

In [13]:
df = pd.read_sql_table('mensajeria_estado', mensajeria)
df.head

<bound method NDFrame.head of    id                  nombre             descripcion
0   4  Recogido por mensajero  Recogido por mensajero
1   5    Entregado en destino    Entregado en destino
2   3             Con novedad           Tiene novedad
3   6      Terminado completo      Terminado completo
4   1                Iniciado   Creado por el usuario
5   2  Con mensajero Asignado  Con mensajero Asignado>

In [14]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 50)
df = pd.read_sql_table('mensajeria_novedadesservicio', mensajeria)
df.head(100).T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
id,4,5,6,7,8,9,10,11,12,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105
fecha_novedad,2023-11-30 05:00:00+00:00,2023-11-30 05:00:00+00:00,2023-11-30 05:00:00+00:00,2023-11-30 05:00:00+00:00,2023-11-30 05:00:00+00:00,2023-11-30 05:00:00+00:00,2023-11-30 05:00:00+00:00,2023-11-30 05:00:00+00:00,2023-11-30 05:00:00+00:00,2023-12-07 05:00:00+00:00,2023-12-07 05:00:00+00:00,2023-12-07 05:00:00+00:00,2023-12-09 05:00:00+00:00,2023-12-28 16:00:14.053979+00:00,2023-12-28 16:01:17.471902+00:00,2023-12-28 16:01:38.521117+00:00,2023-12-28 19:02:01.193737+00:00,2024-01-03 05:00:00+00:00,2024-01-03 05:00:00+00:00,2024-01-04 00:15:49.827327+00:00,2024-01-04 05:00:00+00:00,2024-01-03 05:00:00+00:00,2024-01-04 05:00:00+00:00,2024-01-11 05:00:00+00:00,2024-01-11 05:00:00+00:00,2024-01-11 19:36:21.010444+00:00,2024-01-11 19:37:29.033626+00:00,2024-01-19 00:53:14.973138+00:00,2024-01-23 21:39:31.823434+00:00,2024-01-24 17:31:11.033341+00:00,2024-01-24 20:02:40.482832+00:00,2024-01-24 20:03:07.583583+00:00,2024-01-25 16:25:01.429005+00:00,2024-01-25 16:58:35.888847+00:00,2024-01-25 18:30:48.652746+00:00,2024-01-25 18:31:50.652155+00:00,2024-01-25 18:44:13.266945+00:00,2024-01-25 19:52:39.193810+00:00,2024-01-25 20:19:51.980763+00:00,2024-01-25 20:34:12.633982+00:00,2024-01-25 20:45:12.311557+00:00,2024-01-26 14:47:12.522890+00:00,2024-01-26 14:47:13.338647+00:00,2024-01-26 16:26:40.052097+00:00,2024-01-26 22:58:07.989245+00:00,2024-01-26 23:05:15.558305+00:00,2024-01-26 23:06:46.722259+00:00,2024-01-27 18:12:14.491548+00:00,2024-01-27 18:12:16.674711+00:00,2024-01-27 18:20:19.983153+00:00,2024-01-29 00:02:21.211620+00:00,2024-01-29 16:24:10.804182+00:00,2024-01-29 18:40:24.943103+00:00,2024-01-29 18:54:00.266067+00:00,2024-01-30 15:21:26.954263+00:00,2024-01-30 15:44:29.334285+00:00,2024-01-30 23:45:12.065779+00:00,2024-01-31 14:27:03.029728+00:00,2024-01-31 14:34:28.301561+00:00,2024-01-31 14:34:47.105681+00:00,2024-01-31 15:58:02.464946+00:00,2024-01-31 18:44:03.874633+00:00,2024-01-31 19:46:04.391666+00:00,2024-01-31 22:11:00.378470+00:00,2024-01-31 23:06:26.171137+00:00,2024-02-01 04:55:00.434629+00:00,2024-02-01 13:47:56.406232+00:00,2024-02-01 14:32:48.482782+00:00,2024-02-01 14:32:49.755059+00:00,2024-02-01 17:06:25.415723+00:00,2024-02-02 15:25:23.074038+00:00,2024-02-02 16:29:59.602667+00:00,2024-02-03 14:33:14.871331+00:00,2024-02-03 15:14:23.320421+00:00,2024-02-03 15:32:40.716766+00:00,2024-02-03 15:41:13.893405+00:00,2024-02-04 16:15:40.758223+00:00,2024-02-04 17:47:10.153102+00:00,2024-02-04 20:29:16.027285+00:00,2024-02-04 21:03:31.192009+00:00,2024-02-04 21:05:54.816598+00:00,2024-02-04 21:25:33.637278+00:00,2024-02-04 21:34:08.886274+00:00,2024-02-05 16:43:07.718800+00:00,2024-02-05 21:28:02.859403+00:00,2024-02-05 21:28:28.777277+00:00,2024-02-05 21:30:45.368638+00:00,2024-02-06 01:41:50.512302+00:00,2024-02-06 01:41:52.534713+00:00,2024-02-06 12:46:28.911109+00:00,2024-02-06 16:05:43.291457+00:00,2024-02-06 16:51:44.185130+00:00,2024-02-06 20:59:33.001682+00:00,2024-02-06 22:30:56.084908+00:00,2024-02-06 22:30:56.923847+00:00,2024-02-07 15:20:18.589179+00:00,2024-02-07 20:03:36.193325+00:00,2024-02-07 20:46:19.966357+00:00,2024-02-07 22:40:53.297263+00:00,2024-02-08 01:58:53.617062+00:00
tipo_novedad_id,1,1,1,1,1,2,2,2,1,2,1,1,2,2,1,2,2,2,1,1,1,1,2,1,2,1,1,2,2,1,1,2,2,1,1,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,2,2,1,2,1,1,1,2,1,1,2,2,1,2,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,1,2,2,1,1,1,1,1,1,1,1,1,1,2,1,1,2
descripcion,A,Halo,A,B,A,V,V,C,B,Me pinché,Esperando muestras,Muestras listas,No puedo seguir,X,X,,no puedo continuar,No puedo seguir,Me acabe de pinchar,DEMORA,Hay trancon en la calle 5,V,Se me apagó la moto no quiere prender,Me pinche,Me vare estoy en la carrera 1 con 34,Esperando pedido en el almacen,Novedad desde la app movil,Me pinche,La moto no quiere funcionar,Me demoro estoy oinchado,Me pinche,Me vare estoy por las cancha panamericanas,Lo toma yulieth,En taller alianza no lo hay,Arrima a dfm y no hay repuesto similar,Me vare la moto no quiere prender,Me vare me encuentro en carrera 23 10 56,Arrime a dfm no hay mx similar,Demora en la recta cali Palmira me paro trabsito,Arrime a celeste no ha repuesto igual,No hoy,Esperando a que reciban los medicamentos,Esperando a que reciban los medicamentos,Buscando en el huv los funcionarios para recla...,Novedad,novedad antes de finalizar,segunda novedad antes del terminar,El cliente acepta dejar el repuesto\nY firma f...,El cliente acepta dejar el repuesto\nY firma f...,Se cancela el servicio cliente no contesta se ...,Estoy en trauma pero estoy esperando otras mx ...,En espera a que llegue el encargado de entrega...,Secretaria estaba cerrado se deja mx en torres...,Ok,Termino el servicio,Por cambio de ruta,Demora,Por fallas ni puede cargar el servicio,Por una falla no se pudo montar el servicio te...,Se cayó el sistema,Esperando respuesta del proveedor,En bodega 3 solo recojo un repuesto el otro in...,En automarcali no se recoje repuesto de de la ...,No puedo continuar 31 01,No se despacha x q bodega no entrega copia,Oops,"Proveedor, el arranque, no lo hay\nLo voy a ...","El terminal que traje de muestra, si aplica, ...","El terminal que traje de muestra, si aplica, ...",Cerrado en alianza se entrega cuando habran,Igual le informe a Juan al cel,Buenos días actualmente está suspendido el ser...,"Buenos días señoras y señores, estoy donde el ...","Buenos días, el servicio está suspendido",Me encuentro en Redox y me informa Sebastián q...,Cerrado el local,Vxvx,V,Me pinche,Xb,No puedo porquecmecacidenre,Me vare,Se to,"Autorizada compra, de acuerdo a la consulta, e...",Vvv,Me informas que no se está mandando nada por c...,Adicional con unos glóbulos,Se toma y se deja anotacion en la app pero no ...,Se toma y se deja anotacion en la app pero no ...,Willian roa CC 91528823,No aparecen las mx,"Se recoge la consignación 2pm, enterado Freddy...",Se envía devolución de mercado libre con el co...,El cliente hace el pago por transferencia por ...,El cliente hace el pago por transferencia por ...,Se entrega factura frep 54172 para que sea leg...,Recojido por Cristian roa,Por favor arrimar la mx al laboratorio están h...,Servicio duplicado,Novedad
servicio_id,51,51,51,51,51,51,51,51,29,29,57,57,57,68,68,68,73,81,80,85,84,88,90,94,94,83,83,99,129,144,140,140,157,160,161,161,161,165,168,157,170,178,178,177,187,187,187,203,203,206,219,231,249,258,287,288,79,289,289,289,339,351,356,81,372,377,382,382,382,399,445,454,505,514,516,516,377,187,540,540,515,541,541,558,589,585,578,579,579,600,617,622,636,637,637,637,711,739,732,759
es_prueba,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,False,True,True,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
mensajero_id,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,29,29,7,7,29,3,3,3,3,3,3,3,3,3,3,3,3,8,3,3,3,7,7,7,8,8,19,3,27,17,3,17,17,7,17,17,17,8,24,34,7,25,7,8,8,8,25,8,3,8,3,38,38,7,7,7,7,3,3,18,8,7,37,3,25,25,3,3,8,22,22,22,22,16,3,16,7

In [15]:
tabla_estados = pd.read_sql_table('mensajeria_estadosservicio', mensajeria)
tabla_estados.head(100)

,id,fecha,hora,foto,observaciones,estado_id,servicio_id,es_prueba,foto_binary
0,1014,2024-01-29,01:13:32,foto,4 tubos,4,226,False,None
1,1484,2024-01-30,18:45:12,foto,Demora,3,79,True,None
2,2829,2024-02-06,11:34:04,foto,Compra exitosa,5,613,False,None
3,1888,2024-02-01,14:50:39,foto,Zzxzz,4,376,False,None
4,32312,2024-04-06,16:11:21,foto,No,3,7164,True,None
...,...,...,...,...,...,...,...,...,...
95,40593,2024-04-19,11:39:04,foto,Recibido David,5,8866,False,None
96,40698,2024-04-19,13:04:25,foto,Recibe gina,5,9052,False,None
97,41380,2024-04-20,13:56:47,foto,Recibe Andrés,5,9158,False,None
98,41717,2024-04-22,10:17:32,foto,Recibe francy,6,9283,False,None
99,42264,2024-04-22,17:06:28,foto,Con mensajero Asignado,2,9419,True,None

In [17]:
tabla_estados['estado_id'].value_counts()

estado_id
2    30249
1    29627
4    27542
5    27335
6     8447
3     5202
Name: count, dtype: int64

In [ ]:
columnas_hora = [
    'hora_iniciado',
    'hora_mensajero_asignado',
    'hora_recogido_mensajero',
    'hora_entregado',
    'hora_finalizado_completo'
]

for col in columnas_hora:
    if col in trans_servicio.columns:
        trans_servicio[col] = trans_servicio[col].apply(
            lambda t: t.strftime('%H:%M:%S') if pd.notna(t) else t
        )